name: Publish on Docker Hub and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest version
      uses: actions/checkout@v2

    - name: Push to docker hub
      uses: docker/build-push-action/@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: ${{secrets.DOCKERHUB_REPO}}
        tag_with_ref: true