name: Publish on Docker Hub and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest version
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_REPO}}:$(date +%s)